### ISSUE TITLE
编译失败（import path does not begin with hostname）

### ISSUE THREAD

**Issue by ztc1997** [kitech/toxtun#7]
编译得到错误

```
package gopp: unrecognized import path "gopp" (import path does not begin with hostname)
package tox: unrecognized import path "tox" (import path does not begin with hostname)
```

是我的打开方式不对吗

**Comment by kitech** [comment]
不是你的问题？这两个包需要手工调整一下。
cd $GOPATH/src
git clone https://github.com/kitech/go-toxcore.git tox
git clone https://github.com/kitech/goplusplus.git gopp

现在只支持linux系统。

**Comment by xhebox** [comment]
@ztc1997 本地编译已经可以正常通过了 https://github.com/kitech/toxtun/pull/8

**Comment by kitech** [comment]
谢谢 @xhebox  的修正，现在可以直接  go get 摘取了
